"""
GMSH Geometry Exporter for Bohemien_Motor_Designer.

Converts StatorGeometry + SPMRotorGeometry/IPMRotorGeometry + WindingLayout
into a parametric GMSH .geo script suitable for 2D transient FEA.

Features
--------
- Parametric loop-based slot generation (For/EndFor)
- SPM rotor: arc-segment magnets at rotor OD
- IPM rotor: rectangular magnet pockets subtracted from rotor iron sector
- 2-layer winding: each slot/layer assigned to correct phase and direction
- Sliding surface: circle at air gap mid-radius for Mortar BC
- Physical groups assigned from IndexRegistry (consistent with SIF generator)
- Mesh size graded: fine at air gap, coarser at yoke

Usage
-----
    from Bohemien_Motor_Designer.fea.gmsh_exporter import GMSHExporter
    from Bohemien_Motor_Designer.fea.index_registry import IndexRegistry

    reg = IndexRegistry(poles=motor.poles, slots=motor.slots)
    exp = GMSHExporter(motor, reg)
    exp.write("PMSM.geo")
"""
from __future__ import annotations
import math
import numpy as np
from pathlib import Path
from typing import Optional

from Bohemien_Motor_Designer.fea.index_registry import IndexRegistry
from Bohemien_Motor_Designer.core.geometry.rotor import SPMRotorGeometry, IPMRotorGeometry


class GMSHExporter:
    """
    Writes a GMSH .geo script from a Bohemien_Motor_Designer PMSM motor object.

    Parameters
    ----------
    motor   : PMSM instance (needs stator, rotor_geo, winding, airgap, etc.)
    registry: IndexRegistry shared with SIFGenerator
    lc_gap  : mesh size at air gap [m]  (default: airgap / 3)
    lc_yoke : mesh size at stator yoke [m]  (default: yoke_thickness / 4)
    """

    def __init__(self, motor, registry: IndexRegistry,
                 lc_gap: Optional[float] = None,
                 lc_yoke: Optional[float] = None):
        self.m   = motor
        self.reg = registry

        g = motor.airgap
        self.lc_gap  = lc_gap  if lc_gap  else max(g / 3.0, 0.0003)
        self.lc_yoke = lc_yoke if lc_yoke else max(
            (motor.stator.yoke_thickness if motor.stator else 0.02) / 4.0, 0.002)

        # Winding table: list of CoilSide objects
        self._coils = motor.winding._table if motor.winding else []

    # ── Public API ────────────────────────────────────────────────────────

    def write(self, path: str) -> Path:
        """Write the .geo file and return the Path."""
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        geo = self._generate()
        p.write_text(geo, encoding="utf-8")
        return p

    def geo_string(self) -> str:
        """Return the .geo file content as a string (without writing)."""
        return self._generate()

    # ── Internal generation ───────────────────────────────────────────────

    def _generate(self) -> str:
        m   = self.m
        reg = self.reg
        lines: list[str] = []

        def L(s=""):
            lines.append(s)

        # ── Header ──
        L("// GMSH geometry generated by Bohemien_Motor_Designer GMSHExporter")
        L(f"// Motor: {m.poles}p/{m.slots}s  "
          f"Prated={m.rated_power/1000:.0f}kW  n={m.rated_speed:.0f}rpm")
        L()
        L("SetFactory(\"OpenCASCADE\");")
        L()

        # ── Parameters ──
        stator   = m.stator
        rg       = m.rotor_geo
        R_ro     = m.rotor_outer_radius            # rotor OD
        R_ri     = m.rotor_inner_radius            # shaft radius
        R_si     = stator.inner_radius             # stator bore
        R_so     = stator.outer_radius             # stator OD
        g        = m.airgap
        R_slide  = (R_ro + R_si) / 2.0            # sliding surface radius
        Qs       = m.slots
        p        = m.poles
        sp       = stator.slot_profile

        slot_depth  = sp.depth()
        slot_width  = sp.area() / (slot_depth + 1e-9)  # mean width
        slot_open   = sp.opening_width()
        wedge_h     = getattr(sp, "wedge_height", 0.0)
        tooth_w     = stator.tooth_width
        slot_pitch  = 2 * math.pi * R_si / Qs     # in radians
        half_sw_ang = math.asin(min(slot_width / (2 * R_si), 0.999))
        half_so_ang = math.asin(min(slot_open  / (2 * R_si), 0.999))

        L("// -- Key dimensions --")
        L(f"R_ro    = {R_ro:.6f};   // rotor outer radius")
        L(f"R_ri    = {R_ri:.6f};   // shaft radius")
        L(f"R_si    = {R_si:.6f};   // stator inner radius (bore)")
        L(f"R_so    = {R_so:.6f};   // stator outer radius")
        L(f"R_slide = {R_slide:.6f}; // sliding surface radius")
        L(f"airgap  = {g:.6f};")
        L(f"Qs      = {Qs};         // stator slots")
        L(f"p2      = {p};          // poles (2p)")
        L(f"lc_gap  = {self.lc_gap:.4f};  // mesh size at air gap")
        L(f"lc_yoke = {self.lc_yoke:.4f}; // mesh size at yoke")
        L()

        # ── Stator outer boundary ──
        L("// -- Stator outer boundary --")
        L(f"Circle(1) = {{0, 0, 0, R_so, 0, 2*Pi}};")
        L(f"Curve Loop(1) = {{1}};")
        L()

        # ── Stator bore (inner circle) ──
        L("// -- Stator inner bore --")
        L(f"Circle(2) = {{0, 0, 0, R_si, 0, 2*Pi}};")
        L()

        # ── Sliding surface ──
        L("// -- Sliding surface (Mortar BC) --")
        L(f"Circle(3) = {{0, 0, 0, R_slide, 0, 2*Pi}};")
        L(f"Curve Loop(3) = {{3}};")
        L()

        # ── Rotor outer & inner ──
        L("// -- Rotor --")
        L(f"Circle(4) = {{0, 0, 0, R_ro, 0, 2*Pi}};")
        L(f"Circle(5) = {{0, 0, 0, R_ri, 0, 2*Pi}};")
        L(f"Curve Loop(5) = {{5}};")
        L()

        # ── Slots ──
        L("// -- Stator slots --")
        L(f"slot_pitch_rad = 2*Pi / {Qs};")
        L(f"half_sw = {half_sw_ang:.6f};   // half slot-width angle at bore")
        L(f"half_so = {half_so_ang:.6f};   // half slot-opening angle at bore")
        L(f"slot_depth  = {slot_depth:.6f};")
        L(f"wedge_h     = {wedge_h:.6f};")
        L()

        # Each slot is split into two Plane Surfaces — one per winding layer.
        # Layer 0 = near bore, Layer 1 = near yoke.
        # A mid-depth arc divides the two halves; each gets its own Physical Surface.
        # Curve conventions (all CCW in slot frame):
        #   c_bore : bore opening arc  p_ol → p_or  (CCW on bore circle)
        #   c_lw   : left wedge line   p_ol → p_wl
        #   c_rw   : right wedge line  p_or → p_wr
        #   c_lu   : left upper wall   p_wl → p_ml
        #   c_ru   : right upper wall  p_wr → p_mr
        #   c_mid  : mid arc           p_ml → p_mr  (CCW)
        #   c_ll   : left lower wall   p_ml → p_bl
        #   c_rl   : right lower wall  p_mr → p_br
        #   c_bot  : bottom arc        p_bl → p_br  (CCW)
        # Layer 0 CCW loop: {c_bore, c_rw, c_ru, -c_mid, -c_lu, -c_lw}
        # Layer 1 CCW loop: {c_mid, c_rl, -c_bot, -c_ll}
        # Full slot CCW loop (for stator iron hole):
        #                   {c_bore, c_rw, c_ru, c_rl, -c_bot, -c_ll, -c_lu, -c_lw}
        slot_full_cls  = []   # full-slot curve loops (holes in stator iron)
        layer_surfaces = {}   # {si: [surf_layer0_id, surf_layer1_id]}
        curve_id   = 100
        point_id   = 1000
        surface_id = 100

        for si in range(Qs):
            ac = si * 2 * math.pi / Qs + math.pi / Qs   # slot centre angle
            r_top = R_si + wedge_h                        # top of conductor region
            r_mid = R_si + wedge_h + (slot_depth - wedge_h) / 2.0
            r_bot = R_si + slot_depth
            lc_s  = self.lc_gap

            # ── 8 corner points ───────────────────────────────────────────
            def pt(r, ang):
                nonlocal point_id
                pid = point_id; point_id += 1
                lc  = lc_s if r < r_mid else lc_s * 2
                L(f"Point({pid}) = {{{r*math.cos(ang):.6f}, {r*math.sin(ang):.6f}, 0, {lc:.7f}}};")
                return pid

            L(f"// slot {si}")
            # bore opening corners (p_ol left, p_or right)
            p_ol = pt(R_si, ac - half_so_ang)
            p_or = pt(R_si, ac + half_so_ang)
            # wide corners at bore+wedge
            p_wl = pt(r_top, ac - half_sw_ang)
            p_wr = pt(r_top, ac + half_sw_ang)
            # mid-depth corners
            p_ml = pt(r_mid, ac - half_sw_ang)
            p_mr = pt(r_mid, ac + half_sw_ang)
            # bottom corners
            p_bl = pt(r_bot, ac - half_sw_ang)
            p_br = pt(r_bot, ac + half_sw_ang)

            # ── Arc centre points ─────────────────────────────────────────
            def arc_ctr(r):
                nonlocal point_id
                pid = point_id; point_id += 1
                L(f"Point({pid}) = {{{r*math.cos(ac):.6f}, {r*math.sin(ac):.6f}, 0, {lc_s:.7f}}};")
                return pid

            p_oc  = arc_ctr(R_si)
            p_tc  = arc_ctr(r_top + 1e-6) if wedge_h > 1e-6 else arc_ctr(r_top + 1e-6)
            p_mc  = arc_ctr(r_mid)
            p_bc  = arc_ctr(r_bot)

            # ── Curves ────────────────────────────────────────────────────
            def cid():
                nonlocal curve_id
                c = curve_id; curve_id += 1
                return c

            # bore opening arc: p_ol → p_or  (CCW = increasing angle at R_si)
            c_bore = cid()
            L(f"Circle({c_bore}) = {{{p_ol}, {p_oc}, {p_or}}};")

            # wedge lines: p_ol→p_wl and p_or→p_wr
            c_lw = cid()
            L(f"Line({c_lw}) = {{{p_ol}, {p_wl}}};")
            c_rw = cid()
            L(f"Line({c_rw}) = {{{p_or}, {p_wr}}};")

            # upper conductor walls: p_wl→p_ml and p_wr→p_mr
            c_lu = cid()
            L(f"Line({c_lu}) = {{{p_wl}, {p_ml}}};")
            c_ru = cid()
            L(f"Line({c_ru}) = {{{p_wr}, {p_mr}}};")

            # mid arc: p_ml → p_mr  (CCW)
            c_mid = cid()
            L(f"Circle({c_mid}) = {{{p_ml}, {p_mc}, {p_mr}}};")

            # lower conductor walls: p_ml→p_bl and p_mr→p_br
            c_ll = cid()
            L(f"Line({c_ll}) = {{{p_ml}, {p_bl}}};")
            c_rl = cid()
            L(f"Line({c_rl}) = {{{p_mr}, {p_br}}};")

            # bottom arc: p_bl → p_br  (CCW)
            c_bot = cid()
            L(f"Circle({c_bot}) = {{{p_bl}, {p_bc}, {p_br}}};")

            # ── Surfaces ──────────────────────────────────────────────────
            # Full-slot curve loop (hole for stator iron — no Plane Surface)
            cl_full = surface_id; surface_id += 1
            L(f"Curve Loop({cl_full}) = {{{c_bore}, {c_rw}, {c_ru}, {c_rl}, -{c_bot}, -{c_ll}, -{c_lu}, -{c_lw}}};")
            slot_full_cls.append(cl_full)

            # Layer 0 (near bore): {c_bore, c_rw, c_ru, -c_mid, -c_lu, -c_lw}
            cl0 = surface_id; surface_id += 1
            s0  = cl0
            L(f"Curve Loop({cl0}) = {{{c_bore}, {c_rw}, {c_ru}, -{c_mid}, -{c_lu}, -{c_lw}}};")
            L(f"Plane Surface({s0}) = {{{cl0}}};")

            # Layer 1 (near yoke): {c_mid, c_rl, -c_bot, -c_ll}
            cl1 = surface_id; surface_id += 1
            s1  = cl1
            L(f"Curve Loop({cl1}) = {{{c_mid}, {c_rl}, -{c_bot}, -{c_ll}}};")
            L(f"Plane Surface({s1}) = {{{cl1}}};")

            # Winding phase/direction annotations
            n_layers = m.winding.layers if m.winding else 2
            for layer in range(n_layers):
                wt = reg.winding_tag(si, layer)
                info = self._coil_info(si, layer)
                ph   = "ABC"[info["phase"]] if info else "?"
                sgn  = "+" if (info and info["direction"] > 0) else "-"
                L(f"// winding PS={wt}  slot={si+1}  layer={layer}  {sgn}{ph}")

            layer_surfaces[si] = [s0, s1]
            L()

        L()
        L(f"// {len(slot_full_cls)} slots generated (2 Plane Surfaces each = {len(slot_full_cls)*2} conductor surfaces)")
        L()

        # ── Stator iron surface ──
        L("// -- Stator iron --")
        slot_hole_str = ", ".join(str(x) for x in slot_full_cls)
        L(f"Curve Loop(2) = {{2}};  // bore inner circle")
        L(f"Curve Loop(10) = {{-1}}; // stator OD (inward normal)")
        # Stator iron = disc between OD and bore, with slot holes (full-slot CLs, no Plane Surface)
        L(f"Plane Surface(500) = {{10, 2, {slot_hole_str}}};  // stator iron")
        L()

        # ── Air gap (stator side: between bore and sliding surface) ──
        L("// -- Air gap stator side --")
        L(f"Curve Loop(20) = {{-2}};  // bore (outward from air gap)")
        L(f"Curve Loop(21) = {{3}};   // sliding surface")
        L(f"Plane Surface(501) = {{21, 20}};  // air gap stator side")
        L()

        # ── Rotor geometry ──
        if isinstance(rg, SPMRotorGeometry):
            self._write_spm_rotor(lines, rg, R_ro, R_ri, R_slide,
                                  curve_id, point_id, surface_id)
        elif isinstance(rg, IPMRotorGeometry):
            self._write_ipm_rotor(lines, rg, R_ro, R_ri, R_slide,
                                  curve_id, point_id, surface_id)
        else:
            # Generic: solid rotor iron between shaft and OD
            L("// -- Rotor iron (generic) --")
            L(f"Curve Loop(30) = {{-4}}; // rotor OD (outward from inside)")
            L(f"Curve Loop(31) = {{5}};  // shaft")
            L(f"Plane Surface(502) = {{30, 31}};")
            L(f"Physical Surface({self.reg.rotor_iron}) = {{502}};")

        L()

        # ── Air gap rotor side (between sliding and rotor OD) ──
        L("// -- Air gap rotor side --")
        L(f"Curve Loop(40) = {{-3}};  // sliding surface (outward)")
        L(f"Curve Loop(41) = {{4}};   // rotor OD (inward)")
        L(f"Plane Surface(503) = {{40, 41}};  // air gap rotor side")
        L()

        # ── Physical groups ──
        L("// -- Physical Groups --")
        L(f"Physical Surface({reg.stator_iron}) = {{500}};  // stator iron")
        L(f"Physical Surface({reg.air_gap}) = {{501, 503}}; // all air gap")
        L(f"Physical Surface({reg.shaft}) = {{5}};          // shaft (placeholder)")

        # Winding physical surfaces — one Physical Surface per slot×layer
        # layer_surfaces[si] = [surf_id_layer0, surf_id_layer1]
        for si in range(Qs):
            surfs = layer_surfaces.get(si, [None, None])
            n_layers = m.winding.layers if m.winding else 2
            for layer in range(n_layers):
                wt   = reg.winding_tag(si, layer)
                info = self._coil_info(si, layer)
                surf_id = surfs[layer] if surfs and layer < len(surfs) else None
                if info and surf_id is not None:
                    phase_str = "ABC"[info["phase"]]
                    sign_str  = "+" if info["direction"] > 0 else "-"
                    L(f"Physical Surface({wt}) = {{{surf_id}}};  "
                      f"// slot {si+1} layer {layer}: {sign_str}{phase_str}")
                elif surf_id is not None:
                    L(f"Physical Surface({wt}) = {{{surf_id}}};  // slot {si+1} layer {layer}")

        L()
        L(f"Physical Curve({reg.outer_boundary})  = {{1}};   // outer boundary")
        L(f"Physical Curve({reg.sliding_surface}) = {{3}};   // sliding surface")
        L()

        # ── Mesh settings ──
        L("// -- Mesh settings --")
        L("Mesh.Algorithm = 6;      // Frontal-Delaunay")
        L("Mesh.RecombineAll = 0;   // triangles")
        L("Mesh.CharacteristicLengthExtendFromBoundary = 1;")
        L(f"Mesh.CharacteristicLengthMax = {self.lc_yoke:.4f};")
        L(f"Mesh.CharacteristicLengthMin = {self.lc_gap / 3:.5f};")
        L()

        return "\n".join(lines)

    # ── Rotor writers ─────────────────────────────────────────────────────

    def _write_spm_rotor(self, lines, rg: SPMRotorGeometry,
                          R_ro, R_ri, R_slide, cid, pid, sid):
        def L(s=""):
            lines.append(s)

        p      = self.m.poles
        alpha  = rg.magnet_width_fraction
        t_m    = rg.magnet_thickness
        R_mi   = R_ro - t_m          # magnet inner radius
        reg    = self.reg

        L("// -- SPM Rotor --")
        L(f"// {p} surface magnets, arc fraction alpha_p={alpha:.3f}")
        L()

        surface_ids_iron = []
        surface_ids_pm   = []

        for pole in range(p):
            angle_centre  = pole * 2 * math.pi / p
            half_mag_ang  = math.pi * alpha / p   # half-angle of magnet arc
            ang_l = angle_centre - half_mag_ang
            ang_r = angle_centre + half_mag_ang

            # Four corner points of magnet
            pt_oi = pid; pid += 1   # outer-inner left
            pt_oo = pid; pid += 1   # outer-outer left
            pt_io = pid; pid += 1   # inner-outer right  (confusing naming: use positions)
            pt_ii = pid; pid += 1   # inner-inner right

            xol = R_ro * math.cos(ang_l);  yol = R_ro * math.sin(ang_l)
            xor = R_ro * math.cos(ang_r);  yor = R_ro * math.sin(ang_r)
            xil = R_mi * math.cos(ang_l);  yil = R_mi * math.sin(ang_l)
            xir = R_mi * math.cos(ang_r);  yir = R_mi * math.sin(ang_r)

            lc = self.lc_gap
            L(f"// Magnet pole {pole}")
            L(f"Point({pt_oi}) = {{{xol:.6f},{yol:.6f},0,{lc}}};")
            L(f"Point({pt_oo}) = {{{xor:.6f},{yor:.6f},0,{lc}}};")
            L(f"Point({pt_io}) = {{{xil:.6f},{yil:.6f},0,{lc}}};")
            L(f"Point({pt_ii}) = {{{xir:.6f},{yir:.6f},0,{lc}}};")

            # Outer arc: centre to ang_l → ang_r at R_ro
            p_oc = pid; pid += 1
            xoc = math.cos(angle_centre) * R_ro
            yoc = math.sin(angle_centre) * R_ro
            L(f"Point({p_oc}) = {{{xoc:.6f},{yoc:.6f},0,{lc}}};")

            c_outer = cid; cid += 1
            L(f"Circle({c_outer}) = {{{pt_oi},{p_oc},{pt_oo}}};")

            # Inner arc at R_mi
            p_ic = pid; pid += 1
            xic = math.cos(angle_centre) * R_mi
            yic = math.sin(angle_centre) * R_mi
            L(f"Point({p_ic}) = {{{xic:.6f},{yic:.6f},0,{lc}}};")

            c_inner = cid; cid += 1
            L(f"Circle({c_inner}) = {{{pt_io},{p_ic},{pt_ii}}};")

            c_left  = cid; cid += 1
            c_right = cid; cid += 1
            L(f"Line({c_left})  = {{{pt_oi},{pt_io}}};")
            L(f"Line({c_right}) = {{{pt_ii},{pt_oo}}};")

            cl = sid; sid += 1
            L(f"Curve Loop({cl}) = {{{c_left},{-c_inner},{c_right},{c_outer}}};")
            L(f"Plane Surface({cl}) = {{{cl}}};")
            surface_ids_pm.append((pole, cl))

        # Rotor iron: annulus between shaft and magnet inner radius
        # minus the magnet surfaces (handled as embedded regions in GMSH)
        pm_surf_str = ", ".join(str(s) for _, s in surface_ids_pm)
        L()
        L("// Rotor iron surface (annulus at R_mi, excluding PMs)")
        # Simple annulus rotor_iron — in practice the PM surfaces are embedded
        L(f"Curve Loop(50) = {{-4}};  // rotor OD")
        L(f"Curve Loop(51) = {{5}};   // shaft bore")
        L(f"Plane Surface(504) = {{50, 51}};  // rotor iron (PMs embedded by GMSH)")
        L()

        L(f"Physical Surface({reg.rotor_iron}) = {{504}};  // rotor iron")
        for pole, s in surface_ids_pm:
            L(f"Physical Surface({reg.pm_tag(pole)}) = {{{s}}};  // PM pole {pole}")

    def _write_ipm_rotor(self, lines, rg: IPMRotorGeometry,
                          R_ro, R_ri, R_slide, cid, pid, sid):
        def L(s=""):
            lines.append(s)

        p   = self.m.poles
        b   = rg.barriers[0]
        reg = self.reg
        t_m = b.magnet_thickness
        w_m = b.magnet_width
        ang = b.barrier_angle_deg * math.pi / 180.0

        L("// -- IPM Rotor (V-type, single layer) --")
        L(f"// {p} poles, magnet: {w_m*1e3:.1f}mm × {t_m*1e3:.1f}mm, angle={b.barrier_angle_deg}°")
        L()

        surface_ids_pm = []

        for pole in range(p):
            centre_ang = pole * 2 * math.pi / p

            # Each pole has two magnets (left and right of V)
            for side, sign in enumerate([-1, 1]):
                # Magnet centre position in rotor reference
                r_c   = R_ro - R_ri
                r_mag = R_ri + r_c * 0.55   # magnet radial position (~55% of rotor depth)
                x_off = r_mag * math.cos(centre_ang)
                y_off = r_mag * math.sin(centre_ang)

                # Magnet rectangle corners (rotated by barrier angle)
                rot = centre_ang + sign * (math.pi / 2 - ang)
                hw  = w_m / 2
                ht  = t_m / 2
                corners = [
                    ( hw,  ht), (-hw,  ht),
                    (-hw, -ht), ( hw, -ht),
                ]
                pts = []
                for (cx, cy) in corners:
                    xr = cx * math.cos(rot) - cy * math.sin(rot) + x_off
                    yr = cx * math.sin(rot) + cy * math.cos(rot) + y_off
                    pts.append((pid, xr, yr))
                    L(f"Point({pid}) = {{{xr:.6f},{yr:.6f},0,{self.lc_gap*2}}};")
                    pid += 1

                # Rectangular pocket lines
                cls = []
                for k in range(4):
                    L(f"Line({cid}) = {{{pts[k][0]},{pts[(k+1)%4][0]}}}; ")
                    cls.append(cid)
                    cid += 1

                cl = sid; sid += 1
                L(f"Curve Loop({cl}) = {{{','.join(str(c) for c in cls)}}};")
                L(f"Plane Surface({cl}) = {{{cl}}};")
                pm_idx = pole * 2 + side
                if pm_idx < p:   # only register up to p PM bodies
                    surface_ids_pm.append((pm_idx, cl))

        L()
        L(f"Curve Loop(60) = {{-4}};")
        L(f"Curve Loop(61) = {{5}};")
        pm_surf_list = ", ".join(str(s) for _, s in surface_ids_pm)
        L(f"Plane Surface(505) = {{60, 61}};  // rotor iron with IPM pockets embedded")
        L()
        L(f"Physical Surface({reg.rotor_iron}) = {{505}};")
        for idx, s in surface_ids_pm:
            if idx < p:
                L(f"Physical Surface({reg.pm_tag(idx)}) = {{{s}}};  // IPM magnet {idx}")

    # ── Helpers ───────────────────────────────────────────────────────────

    def _coil_info(self, slot_idx: int, layer: int) -> Optional[dict]:
        """Return phase/direction dict for slot_idx + layer, or None."""
        if not self._coils:
            return None
        matches = [c for c in self._coils
                   if c.slot_idx == slot_idx and c.layer == layer]
        if not matches:
            return None
        c = matches[0]
        return {"phase": c.phase, "direction": c.direction}
