"""
Elmer SIF (Solver Input File) Generator for Bohemien_Motor_Designer.

Produces two SIF files from a PMSM motor specification:
  case_cogging.sif — rotor position sweep, Id=Iq=0, cogging torque extraction
  case_loaded.sif  — time-transient run at rated operating point, full period

Both files reference the same mesh (generated by GMSH exporter) and the same
BH curve file (generated by bh_writer.py).

Physics
-------
- Magnetostatics (cogging) or time-harmonic (loaded): AV formulation in 2D
- Magnets: remanence Br set via MATC expression, direction follows pole angle
- Windings: current density from inverse Park transform at rated MTPA angle
- Material: nonlinear BH from external file, Elmer NonLinear Material
- Torque: Arkkio Maxwell stress tensor method

Elmer conventions
-----------------
- All quantities in SI
- AV formulation: A_z (scalar) in 2D
- Current density J [A/m²] = (N * I_phase) / (slot_area * fill_factor)
- MATC expressions for angle-dependent quantities

Usage
-----
    from Bohemien_Motor_Designer.fea.sif_generator import SIFGenerator
    from Bohemien_Motor_Designer.fea.index_registry import IndexRegistry

    reg = IndexRegistry(poles=motor.poles, slots=motor.slots)
    gen = SIFGenerator(motor, reg, work_dir="/tmp/fea_run")
    gen.write_cogging_sif()    # → /tmp/fea_run/case_cogging.sif
    gen.write_loaded_sif()     # → /tmp/fea_run/case_loaded.sif
"""
from __future__ import annotations
import math
import numpy as np
from pathlib import Path
from typing import Optional

from Bohemien_Motor_Designer.fea.index_registry import IndexRegistry


class SIFGenerator:
    """
    Generates Elmer SIF files from a Bohemien_Motor_Designer PMSM instance.

    Parameters
    ----------
    motor    : PMSM instance
    registry : IndexRegistry (same object used by GMSHExporter)
    work_dir : directory where SIF files and BH files are written
    bh_file  : path to BH curve file (relative or absolute)
                If None, defaults to work_dir / <lamination_grade>_BH.dat
    n_positions_cogging : number of rotor positions for cogging sweep
    n_steps_loaded      : number of time steps for one electrical period
    """

    def __init__(self, motor, registry: IndexRegistry,
                 work_dir: str = ".",
                 bh_file: Optional[str] = None,
                 n_positions_cogging: int = 31,
                 n_steps_loaded:      int = 60):
        self.m    = motor
        self.reg  = registry
        self.wd   = Path(work_dir)
        self.wd.mkdir(parents=True, exist_ok=True)

        lam_grade = getattr(motor.stator, "lamination", "M270-35A") if motor.stator else "M270-35A"
        self.bh_file = bh_file if bh_file else str(self.wd / f"{lam_grade}_BH.dat")

        self.n_cog     = n_positions_cogging
        self.n_steps   = n_steps_loaded

        # Derived motor quantities
        self._omega_e  = motor.rated_speed * 2 * math.pi / 60 * motor.pole_pairs
        self._period   = 2 * math.pi / self._omega_e   # one electrical period [s]
        self._Br       = motor._get_Br() if hasattr(motor, "_get_Br") else 1.2
        self._mu_r_mag = getattr(motor, "_mu_r", 1.05)

        # Rated dq currents at MTPA
        Iq_rated = motor.rated_torque / (
            1.5 * motor.pole_pairs * motor.back_emf_constant() + 1e-9)
        self._Iq = Iq_rated * math.sqrt(2)   # peak
        self._Id = 0.0                         # SPM MTPA

        # Slot current density
        stator   = motor.stator
        sp       = stator.slot_profile if stator else None
        slot_A   = sp.area() if sp else 1e-4
        ff       = getattr(motor, "slot_fill_factor", 0.45)
        N_coil   = getattr(motor, "turns_per_coil", 10)
        self._J_peak = (N_coil * self._Iq) / (slot_A * ff + 1e-9)   # A/m²

    # ── Public API ────────────────────────────────────────────────────────

    def write_cogging_sif(self) -> Path:
        """Write case_cogging.sif — static sweep over rotor positions."""
        content = self._cogging_sif()
        p = self.wd / "case_cogging.sif"
        p.write_text(content, encoding="utf-8")
        return p

    def write_loaded_sif(self) -> Path:
        """Write case_loaded.sif — time-transient at rated operating point."""
        content = self._loaded_sif()
        p = self.wd / "case_loaded.sif"
        p.write_text(content, encoding="utf-8")
        return p

    # ── SIF builders ─────────────────────────────────────────────────────

    def _cogging_sif(self) -> str:
        """
        Cogging torque SIF.
        Static magnetostatics, Id=Iq=0, swept over n_cog rotor positions.
        The rotor position angle theta [rad] is the time-like variable.
        """
        m   = self.m
        reg = self.reg
        p   = m.poles
        Qs  = m.slots

        cog_step   = 2 * math.pi / (Qs * m.pole_pairs)   # one cogging period
        total_ang  = cog_step * (self.n_cog - 1)

        lines = self._header("Cogging torque sweep (Id=Iq=0, static)")

        # ── Simulation ──
        lines += f"""
Header
  Mesh DB "." "PMSM"
  Results Directory "cogging_results"
End

Simulation
  Coordinate System = Cartesian 2D
  Coordinate Mapping(3) = 1 2 3
  Simulation Type = Scanning
  Timestep Sizes(1) = {cog_step / (2*math.pi):.8f}  ! normalised to full revolution
  Timestep Intervals(1) = {self.n_cog}
  Output Intervals(1) = 1
  Steady State Max Iterations = 20
  Max Output Level = 5
End

"""

        # ── Constants ──
        lines += self._constants_block()

        # ── Bodies ──
        lines += self._bodies_block(loaded=False)

        # ── Materials ──
        lines += self._materials_block()

        # ── Magnets (cogging: no current, just PM field) ──
        lines += self._magnet_body_forces(current=False)

        # ── Boundary conditions ──
        lines += self._boundary_conditions()

        # ── Solvers ──
        lines += self._solvers_block(cogging=True)

        return lines

    def _loaded_sif(self) -> str:
        """
        Loaded torque SIF.
        Time-transient, one electrical period at rated speed, rated dq currents.
        """
        m   = self.m
        reg = self.reg

        dt  = self._period / self.n_steps

        lines = self._header("Loaded torque run (rated MTPA operating point)")

        lines += f"""
Header
  Mesh DB "." "PMSM"
  Results Directory "loaded_results"
End

Simulation
  Coordinate System = Cartesian 2D
  Coordinate Mapping(3) = 1 2 3
  Simulation Type = Transient
  Timestep Sizes(1) = {dt:.8e}
  Timestep Intervals(1) = {self.n_steps}
  Output Intervals(1) = 1
  Steady State Max Iterations = 20
  Max Output Level = 5
End

"""

        lines += self._constants_block()
        lines += self._bodies_block(loaded=True)
        lines += self._materials_block()
        lines += self._magnet_body_forces(current=True)
        lines += self._winding_body_forces()
        lines += self._boundary_conditions()
        lines += self._solvers_block(cogging=False)

        return lines

    # ── Block builders ────────────────────────────────────────────────────

    def _header(self, description: str) -> str:
        m = self.m
        return (
            f"! Bohemien_Motor_Designer Elmer SIF - {description}\n"
            f"! Motor: {m.poles}p/{m.slots}s  "
            f"P={m.rated_power/1000:.0f}kW  n={m.rated_speed:.0f}rpm\n"
            f"! Ke={m.back_emf_constant():.4f} Vs/rad  "
            f"Ld={m.Ld*1000:.2f}mH  Lq={m.Lq*1000:.2f}mH\n"
            f"! Iq_rated_peak={self._Iq:.2f}A  J_peak={self._J_peak/1e6:.2f}MA/m2\n\n"
        )

    def _constants_block(self) -> str:
        return (
            "Constants\n"
            "  Permittivity of Vacuum = 8.8542e-12\n"
            "  Permeability of Vacuum = 1.2566e-06\n"
            "End\n\n"
        )

    def _bodies_block(self, loaded: bool) -> str:
        reg = self.reg
        m   = self.m
        s   = ""

        # Body IDs: use physical surface tags directly as body IDs
        # (ElmerGrid maps PS → body when using -in mode)
        bodies = {
            "Stator iron":  (reg.stator_iron, "Stator Iron"),
            "Rotor iron":   (reg.rotor_iron,  "Rotor Iron"),
            "Air gap":      (reg.air_gap,     "Air Gap"),
            "Shaft":        (reg.shaft,       "Shaft"),
        }

        for label, (bid, mat_name) in bodies.items():
            s += f"Body {bid}  ! {label}\n"
            s += f"  Material = {bid}\n"
            s += "End\n\n"

        # PM bodies
        for pole in range(m.poles):
            bid = reg.pm_tag(pole)
            s += f"Body {bid}  ! PM pole {pole}\n"
            s += f"  Material = {bid}\n"
            angle_deg = pole * 360.0 / m.poles
            s += f"  Body Force = {bid}  ! Br direction @ {angle_deg:.1f} deg\n"
            s += "End\n\n"

        # Winding bodies (loaded run only — cogging has J=0)
        if loaded:
            for si in range(m.slots):
                for layer in range(m.winding.layers if m.winding else 2):
                    wt = reg.winding_tag(si, layer)
                    s += f"Body {wt}  ! slot {si+1} layer {layer}\n"
                    s += f"  Material = {reg.air_gap}  ! conductor (air equiv.)\n"
                    s += f"  Body Force = {wt}\n"
                    s += "End\n\n"

        return s

    def _materials_block(self) -> str:
        reg = self.reg
        m   = self.m

        s = ""

        # Stator iron — nonlinear from BH file
        bid = reg.stator_iron
        s += f"Material {bid}  ! Stator iron\n"
        s += f"  Name = \"Stator Iron\"\n"
        s += f"  Relative Permeability = 1.0\n"  # overridden by H-B curve
        s += f"  H-B Curve = Variable time\n"
        s += f"    Real MATC \"Interp1('{self.bh_file}',$1)\"\n"
        s += f"  Electric Conductivity = 0.0  ! laminated\n"
        s += "End\n\n"

        # Rotor iron — same grade for now
        bid_ri = reg.rotor_iron
        s += f"Material {bid_ri}  ! Rotor iron\n"
        s += f"  Name = \"Rotor Iron\"\n"
        s += f"  Relative Permeability = 1.0\n"
        s += f"  H-B Curve = Variable time\n"
        s += f"    Real MATC \"Interp1('{self.bh_file}',$1)\"\n"
        s += f"  Electric Conductivity = 0.0\n"
        s += "End\n\n"

        # Air gap (and winding slot air)
        bid_ag = reg.air_gap
        s += f"Material {bid_ag}  ! Air gap / winding slot\n"
        s += f"  Name = \"Air\"\n"
        s += f"  Relative Permeability = 1.0\n"
        s += f"  Electric Conductivity = 0.0\n"
        s += "End\n\n"

        # Shaft
        bid_sh = reg.shaft
        s += f"Material {bid_sh}  ! Shaft (non-magnetic steel)\n"
        s += f"  Name = \"Shaft\"\n"
        s += f"  Relative Permeability = 1.0\n"
        s += f"  Electric Conductivity = 0.0\n"
        s += "End\n\n"

        # PM bodies
        for pole in range(m.poles):
            bid = reg.pm_tag(pole)
            s += f"Material {bid}  ! PM pole {pole}\n"
            s += f"  Name = \"PM_pole_{pole}\"\n"
            s += f"  Relative Permeability = {self._mu_r_mag:.4f}\n"
            s += f"  Magnetization 1 = Real 0.0  ! set via Body Force\n"
            s += f"  Magnetization 2 = Real 0.0\n"
            s += f"  Electric Conductivity = 0.0\n"
            s += "End\n\n"

        return s

    def _magnet_body_forces(self, current: bool) -> str:
        """Permanent magnet remanence body forces, one per pole."""
        m    = self.m
        reg  = self.reg
        Br   = self._Br
        mu0  = 4e-7 * math.pi

        s = ""
        for pole in range(m.poles):
            bid   = reg.pm_tag(pole)
            # Magnetisation angle: alternates N/S with each pole
            # Electrical angle of pole centre
            mech_angle = pole * 2 * math.pi / m.poles
            # Alternating polarity: even poles point outward, odd inward
            polarity   = 1 if pole % 2 == 0 else -1
            Mx = polarity * Br / (mu0 * self._mu_r_mag) * math.cos(mech_angle)
            My = polarity * Br / (mu0 * self._mu_r_mag) * math.sin(mech_angle)

            s += f"Body Force {bid}  ! PM pole {pole}\n"
            s += f"  Magnetization 1 = Real {Mx:.4f}\n"
            s += f"  Magnetization 2 = Real {My:.4f}\n"

            if current:
                # Add MATC expression for time-varying angle in transient run
                angle_deg = mech_angle * 180.0 / math.pi
                s += (
                    f"  ! Rotor angle (mech) offset = {angle_deg:.2f} deg\n"
                    f"  ! MATC override for transient: angle = omega_e*t / pole_pairs\n"
                )
            s += "End\n\n"

        return s

    def _winding_body_forces(self) -> str:
        """Phase current body forces for loaded run, using inverse Park transform."""
        m   = self.m
        reg = self.reg

        # Electrical angular frequency
        we   = self._omega_e
        J_pk = self._J_peak
        Id   = self._Id
        Iq   = self._Iq
        p    = m.pole_pairs

        # Phase current amplitudes from dq
        # ia = Id*cos(we*t) - Iq*sin(we*t)  (simplified Park)
        I_pk = math.sqrt(Id**2 + Iq**2)   # peak phase current

        s = "! Winding body forces (current density, time-transient)\n"
        s += f"! I_peak = {I_pk:.2f} A  J_peak = {J_pk/1e6:.2f} MA/m2\n"
        s += f"! omega_e = {we:.2f} rad/s\n\n"

        # MTPA angle for IPMSM (0 for SPM)
        beta = 0.0
        if abs(m.Ld - m.Lq) > 1e-6:
            Id_, Iq_ = m.mtpa_angle(I_pk)
            beta = math.atan2(-Id_, Iq_) if Iq_ > 0 else 0.0

        for si in range(m.slots):
            for layer in range(m.winding.layers if m.winding else 2):
                wt   = reg.winding_tag(si, layer)
                info = self._coil_info(si, layer)
                if not info:
                    continue

                phase   = info["phase"]       # 0=A, 1=B, 2=C
                dir_sgn = info["direction"]   # +1 or -1

                # Phase offset: phase B lags A by 120°, C by 240°
                phase_offset = phase * 2 * math.pi / 3.0

                # Current density MATC expression
                J_expr = (
                    f"{dir_sgn * J_pk:.4f} * "
                    f"cos({we:.4f}*time - {phase_offset:.4f} + {beta:.4f})"
                )

                s += f"Body Force {wt}  ! slot {si+1} layer {layer} "
                s += f"{'+-'[dir_sgn < 0]}{'ABC'[phase]}\n"
                s += f"  Current Density = Real MATC \"{J_expr}\"\n"
                s += "End\n\n"

        return s

    def _boundary_conditions(self) -> str:
        reg = self.reg
        return (
            f"Boundary Condition 1  ! Outer boundary - A_z = 0\n"
            f"  Target Boundaries(1) = {reg.outer_boundary}\n"
            f"  A = Real 0.0\n"
            f"End\n\n"
            f"Boundary Condition 2  ! Sliding surface (Mortar)\n"
            f"  Target Boundaries(1) = {reg.sliding_surface}\n"
            f"  Mortar BC = 1\n"
            f"  Rotational BC = True\n"
            f"End\n\n"
        )

    def _solvers_block(self, cogging: bool) -> str:
        run_type = "Cogging" if cogging else "Loaded"
        s  = f"! -- Solvers ({run_type}) --\n\n"

        # Whitney AV solver
        s += (
            "Solver 1\n"
            "  Equation = \"Mag\"\n"
            "  Variable = A[A re:1 A im:1]\n"
            "  Procedure = \"MagnetoDynamics2D\" \"MagnetoDynamics2D\"\n"
            "  Linear System Solver = Iterative\n"
            "  Linear System Iterative Method = BiCGStab\n"
            "  Linear System Preconditioning = ILU2\n"
            "  Linear System Max Iterations = 1000\n"
            "  Linear System Convergence Tolerance = 1e-10\n"
            "  NonLinear System Max Iterations = 30\n"
            "  NonLinear System Convergence Tolerance = 1e-6\n"
            "  NonLinear System Relaxation Factor = 0.7\n"
            "  Steady State Convergence Tolerance = 1e-6\n"
            "End\n\n"
        )

        # Field computation (derived quantities)
        s += (
            "Solver 2\n"
            "  Equation = CalcFields\n"
            "  Procedure = \"MagnetoDynamics2D\" \"MagnetoDynamics2DCalc\"\n"
            "  Calculate Magnetic Field Strength = True\n"
            "  Calculate Magnetic Flux Density = True\n"
            "  Calculate Current Density = True\n"
            "  Calculate Nodal Fields = True\n"
            "  Steady State Convergence Tolerance = 1e-6\n"
            "End\n\n"
        )

        # Arkkio torque solver
        s += (
            "Solver 3\n"
            "  Equation = Torque\n"
            f"  Procedure = \"SaveData\" \"SaveScalars\"\n"
            f"  File Name = \"{('cogging' if cogging else 'loaded')}_torque.dat\"\n"
            f"  Variable 1 = \"Maxwell Stress Tensor Torque\"\n"
            f"  Operator 1 = \"boundary sum\"\n"
            f"  Target Boundaries(1) = {self.reg.sliding_surface}\n"
            "End\n\n"
        )

        if not cogging:
            # Flux linkage on phase boundaries (for Ld/Lq extraction)
            s += (
                "Solver 4\n"
                "  Equation = FluxLinkage\n"
                "  Procedure = \"SaveData\" \"SaveLine\"\n"
                "  File Name = \"flux_linkage.dat\"\n"
                "  Polyline Coordinates(2,2) = 0.0 -0.085  0.0 0.085\n"
                "  Polyline Divisions = 200\n"
                "End\n\n"
            )

        # Equation applies to all bodies
        all_body_ids = (
            [self.reg.stator_iron, self.reg.rotor_iron,
             self.reg.air_gap, self.reg.shaft]
            + [self.reg.pm_tag(i) for i in range(self.m.poles)]
        )
        if not cogging:
            all_body_ids += [
                self.reg.winding_tag(si, l)
                for si in range(self.m.slots)
                for l in range(self.m.winding.layers if self.m.winding else 2)
            ]

        body_ids_str = " ".join(str(b) for b in sorted(set(all_body_ids)))
        s += (
            f"Equation 1\n"
            f"  Active Solvers(3) = 1 2 3\n"
            f"End\n\n"
        )

        return s

    # ── Helpers ───────────────────────────────────────────────────────────

    def _coil_info(self, slot_idx: int, layer: int):
        if not self.m.winding:
            return None
        matches = [c for c in self.m.winding._table
                   if c.slot_idx == slot_idx and c.layer == layer]
        return {"phase": matches[0].phase, "direction": matches[0].direction} if matches else None
